import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { BriefsEditor } from "@/components/BriefsEditor";
import { QuickSetupButton } from "@/components/QuickSetupButton";
import { BulkBriefAdd } from "@/components/BulkBriefAdd";
import { RunAutopilotNowButton } from "@/components/RunAutopilotNowButton";
import { isDiscoveryConfigured } from "@/lib/discovery";
import {
  nextAutopilotRun,
  nextSendRun,
  formatParisDateTime,
  relativeFromNow,
} from "@/lib/autopilotStatus";
import {
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  Bot,
  Activity,
  Search,
  Database,
  Star,
  PenLine,
  CalendarClock,
  Zap,
  Heart,
} from "lucide-react";

export const dynamic = "force-dynamic";

function utcMidnight(offsetDays = 0): Date {
  const d = new Date();
  d.setUTCHours(0, 0, 0, 0);
  if (offsetDays) d.setUTCDate(d.getUTCDate() + offsetDays);
  return d;
}

export default async function AutopilotPage() {
  const discoveryConfigured = await isDiscoveryConfigured();
  const now = new Date();
  const nextAutopilot = nextAutopilotRun(now);
  const nextSend = nextSendRun(now);

  const todayStart = utcMidnight();
  const tomorrowStart = utcMidnight(1);
  const dayAfter = utcMidnight(2);
  const sevenAgo = utcMidnight(-7);
  const thirtyAgo = utcMidnight(-30);

  const [
    activeBriefs,
    inactiveBriefs,
    sendingTodayInitial,
    sendingTomorrow,
    recentRuns,
    totalProspects,
    discoverQueue,
    enrichedCount,
    scoredCount,
    draftedCount,
    scheduledCount,
    emailsLast7,
    openedLast7,
    repliesLast7,
    failedRuns7,
    bccFailures,
    runsLast30Stats,
    activeFeed,
  ] = await Promise.all([
    prisma.searchBrief.count({ where: { active: true } }),
    prisma.searchBrief.count({ where: { active: false } }),
    prisma.prospect.count({
      where: { status: "Scheduled", scheduledInitial: { gte: todayStart, lt: tomorrowStart } },
    }),
    prisma.prospect.count({
      where: { status: "Scheduled", scheduledInitial: { gte: tomorrowStart, lt: dayAfter } },
    }),
    prisma.discoveryRun.findMany({
      orderBy: { startedAt: "desc" },
      take: 8,
      include: { brief: { select: { name: true } } },
    }),
    prisma.prospect.count(),
    prisma.prospect.count({ where: { createdAt: { gte: thirtyAgo } } }),
    prisma.prospect.count({ where: { siteSnapshotAt: { not: null, gte: thirtyAgo } } }),
    prisma.prospect.count({ where: { qualityScore: { not: null }, createdAt: { gte: thirtyAgo } } }),
    prisma.prospect.count({ where: { autoGenerated: true, createdAt: { gte: thirtyAgo } } }),
    prisma.prospect.count({ where: { status: "Scheduled", createdAt: { gte: thirtyAgo } } }),
    prisma.email.count({ where: { poslat: true, poslatAt: { gte: sevenAgo } } }),
    prisma.email.count({ where: { otvoren: true, poslatAt: { gte: sevenAgo } } }),
    prisma.reply.count({ where: { receivedAt: { gte: sevenAgo } } }),
    prisma.discoveryRun.count({ where: { status: "failed", startedAt: { gte: sevenAgo } } }),
    prisma.email.count({ where: { bccError: { not: null } } }),
    prisma.discoveryRun.aggregate({
      where: { startedAt: { gte: thirtyAgo } },
      _sum: { found: true, created: true, qualified: true, scheduled: true },
    }),
    prisma.email.findMany({
      where: { poslat: true },
      orderBy: { poslatAt: "desc" },
      take: 10,
      select: { id: true, tip: true, poslatAt: true, prospect: { select: { firmaNaziv: true, id: true, language: true } } },
    }),
  ]);

  const autopilotLive = activeBriefs > 0 && discoveryConfigured;
  const openRate7 = emailsLast7 > 0 ? Math.round((openedLast7 / emailsLast7) * 100) : 0;
  const queue = sendingTodayInitial + sendingTomorrow;

  const healthSignals: Array<{ name: string; ok: boolean }> = [
    { name: "Discovery configured", ok: discoveryConfigured },
    { name: "Active briefs", ok: activeBriefs > 0 },
    { name: "Anthropic key", ok: !!process.env.ANTHROPIC_API_KEY },
    { name: "Resend key", ok: !!process.env.RESEND_API_KEY },
    { name: "IMAP reply detection", ok: !!process.env.IMAP_USER },
    { name: "No BCC failures", ok: bccFailures === 0 },
    { name: "Recent runs clean", ok: failedRuns7 < 3 },
  ];
  const healthScore = Math.round((healthSignals.filter((s) => s.ok).length / healthSignals.length) * 100);

  const briefsByCountry = await prisma.searchBrief.groupBy({
    by: ["country"],
    _count: true,
  });
  const byCountry = Object.fromEntries(briefsByCountry.map((g) => [g.country, g._count]));

  const funnelMax = Math.max(discoverQueue, 1);

  return (
    <div className="max-w-[1400px] space-y-3">
      <div className="flex flex-wrap items-end justify-between gap-4 pb-2">
        <div>
          <div className="flex items-center gap-3 mb-3">
            <span className={`pill ${autopilotLive ? "pill-accent" : "pill-warning"}`}>
              <span className={`dot ${autopilotLive ? "dot-live" : ""}`} />
              {autopilotLive ? "Live · 6 fires per business day" : "Paused"}
            </span>
            <span className="text-[10.5px] uppercase tracking-[0.18em] font-semibold text-[var(--text-dim)]">Autopilot</span>
          </div>
          <h1 className="text-white text-4xl sm:text-5xl tracking-tight">
            The system that finds your clients
          </h1>
          <p className="text-[var(--text-muted)] text-sm mt-3 max-w-2xl">
            Discovers, enriches, scores, drafts, schedules. You only open your inbox when a warm lead lands.
          </p>
        </div>
        <RunAutopilotNowButton />
      </div>

      <div className="card card-accent corner-accent p-7">
        <div className="flex flex-wrap items-end justify-between gap-8">
          <div>
            <p className="section-label text-emerald-400/80"><Bot className="w-3 h-3" /> In queue</p>
            <p className="display-number text-white text-[80px] mt-3 leading-none">{queue}</p>
            <p className="text-[var(--text-muted)] text-sm mt-3 font-medium">prospects across {activeBriefs} active briefs</p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-x-8 gap-y-5 flex-1 max-w-2xl">
            <Block label="Next discovery" big={relativeFromNow(nextAutopilot, now)} sub={formatParisDateTime(nextAutopilot)} />
            <Block label="Next send" big={relativeFromNow(nextSend, now)} sub={formatParisDateTime(nextSend)} />
            <Block label="Emails / 7d" big={emailsLast7.toString()} sub={`${repliesLast7} replies · ${openRate7}% open`} />
            <Block label="Failures / 7d" big={failedRuns7.toString()} sub={failedRuns7 === 0 ? "all clean" : "check runs"} tone={failedRuns7 === 0 ? "good" : "warn"} />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
        <div className="card p-6">
          <p className="section-label mb-1"><Bot className="w-3 h-3" /> AI Pipeline (30d)</p>
          <p className="text-[var(--text-dim)] text-xs mb-5">Funnel from discovery to scheduled outreach</p>
          <FunnelRow icon={Search} label="Discover" value={discoverQueue} max={funnelMax} />
          <FunnelRow icon={Database} label="Enrich" value={enrichedCount} max={funnelMax} />
          <FunnelRow icon={Star} label="Score" value={scoredCount} max={funnelMax} />
          <FunnelRow icon={PenLine} label="Draft" value={draftedCount} max={funnelMax} />
          <FunnelRow icon={CalendarClock} label="Schedule" value={scheduledCount} max={funnelMax} last />
          {runsLast30Stats._sum.found !== null && (
            <p className="text-[var(--text-faint)] text-[10px] uppercase tracking-widest mt-4 pt-3 etch-top font-semibold">
              {runsLast30Stats._sum.found ?? 0} found · {runsLast30Stats._sum.created ?? 0} created · {runsLast30Stats._sum.qualified ?? 0} qualified
            </p>
          )}
        </div>

        <div className="card p-6">
          <p className="section-label mb-1"><Activity className="w-3 h-3" /> Live Activity</p>
          <p className="text-[var(--text-dim)] text-xs mb-4">Latest outbound touches</p>
          {activeFeed.length === 0 ? (
            <p className="text-[var(--text-dim)] text-sm py-8 text-center">No sends yet. First fire 07:00 Paris.</p>
          ) : (
            <ul className="space-y-3">
              {activeFeed.map((e) => (
                <li key={e.id} className="flex items-start gap-3 text-xs">
                  <div className="w-7 h-7 rounded-sm flex items-center justify-center shrink-0 bg-emerald-500/10 text-emerald-300 border border-emerald-500/25">
                    <Sparkles className="w-3.5 h-3.5" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <Link href={`/prospects/${e.prospect.id}`} className="text-[var(--text)] hover:text-emerald-300 font-semibold block truncate transition-colors">
                      {e.tip} · {e.prospect.firmaNaziv}
                    </Link>
                    <p className="text-[var(--text-dim)] mt-0.5">
                      {e.prospect.language === "nl" ? "🇳🇱 NL · Dutch" : "🇫🇷 FR · French"}
                    </p>
                  </div>
                  <span className="text-[var(--text-faint)] text-[10px] tabular shrink-0 pt-0.5">{e.poslatAt ? relativeFromNow(e.poslatAt, now) : ""}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="card p-6">
          <p className="section-label mb-1"><Heart className="w-3 h-3" /> System Health</p>
          <div className="flex items-end justify-between mt-3 mb-5">
            <p className={`display-number text-[56px] leading-none ${healthScore >= 80 ? "text-emerald-300" : healthScore >= 60 ? "text-amber-300" : "text-rose-300"}`}>
              {healthScore}
            </p>
            <p className="text-[var(--text-dim)] text-xs font-semibold pb-2">/ 100</p>
          </div>
          <ul className="space-y-2.5">
            {healthSignals.map((s) => (
              <li key={s.name} className="flex items-center justify-between text-xs">
                <span className="text-[var(--text-muted)]">{s.name}</span>
                <span className={`text-[10px] uppercase tracking-wider font-bold ${s.ok ? "text-emerald-300" : "text-amber-300"}`}>
                  {s.ok ? "ok" : "missing"}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {discoveryConfigured && (
        <div className="card p-6">
          <p className="section-label mb-1"><Zap className="w-3 h-3 text-emerald-400" /> Quick Setup — launch a market</p>
          <p className="text-white text-sm mt-1 mb-5 font-semibold">One click seeds 48 curated briefs across three markets.</p>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-5">
            <CountryTile flag="🇫🇷" country="France" active={byCountry.FR ?? 0} highlight="20 briefs · Places + Sirene gov" />
            <CountryTile flag="🇨🇭" country="Switzerland (Romandie)" active={byCountry.CH ?? 0} highlight="12 briefs · Geneva, Lausanne" />
            <CountryTile flag="🇳🇱" country="Netherlands" active={byCountry.NL ?? 0} highlight="16 briefs · Dutch templates" />
          </div>
          <QuickSetupButton hasAnyBrief={activeBriefs + inactiveBriefs > 0} />
        </div>
      )}

      {discoveryConfigured && <BulkBriefAdd />}

      <BriefsEditor discoveryConfigured={discoveryConfigured} />

      {recentRuns.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-3">
            <p className="section-label"><Sparkles className="w-3 h-3 text-emerald-400" /> Recent runs</p>
            <p className="text-[var(--text-dim)] text-xs">{recentRuns.length} shown · {totalProspects} prospects total</p>
          </div>
          <div className="card overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[var(--border-2)] bg-[var(--bg-elev-1)]">
                  {["Brief", "Status", "Found", "Created", "Qualified", "Scheduled", "When"].map((h) => (
                    <th key={h} className="text-left px-4 py-3 text-[var(--text-dim)] text-[10px] uppercase tracking-widest font-bold">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--border-1)]">
                {recentRuns.map((r) => (
                  <tr key={r.id} className="hover:bg-white/[0.02] transition-colors">
                    <td className="px-4 py-3 text-white font-semibold">{r.brief.name}</td>
                    <td className="px-4 py-3">
                      <span className={`pill ${r.status === "done" ? "pill-accent" : r.status === "running" ? "pill-muted" : "pill-danger"}`}>{r.status}</span>
                    </td>
                    <td className="px-4 py-3 text-[var(--text-muted)] tabular">{r.found}</td>
                    <td className="px-4 py-3 text-[var(--text-muted)] tabular">{r.created}</td>
                    <td className="px-4 py-3 text-emerald-300 tabular font-bold">{r.qualified}</td>
                    <td className="px-4 py-3 text-emerald-300 tabular font-bold">{r.scheduled}</td>
                    <td className="px-4 py-3 text-[var(--text-dim)] text-xs tabular">{relativeFromNow(r.startedAt, now)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <div className="card p-6">
        <p className="section-label mb-4">Setup checklist</p>
        <ul className="space-y-2.5 text-sm">
          <CheckItem ok={discoveryConfigured} title="GOOGLE_PLACES_API_KEY" okHint="Google Places live · powers Group A + CH/NL discovery" missingHint="Add to Vercel env (Sirene group still works without it)" />
          <CheckItem ok={!!process.env.IMAP_USER && !!process.env.IMAP_PASSWORD} title="IMAP_USER / IMAP_PASSWORD" okHint="Reply detection 3×/day" missingHint="Without these, replies don't flow back" />
          <CheckItem ok={bccFailures === 0} title="BCC delivery to operator inbox" okHint="All sends logged on Email.bccSentAt" missingHint={`${bccFailures} send(s) failed BCC — see Email.bccError`} />
        </ul>
      </div>
    </div>
  );
}

function Block({ label, big, sub, tone }: { label: string; big: string; sub: string; tone?: "good" | "warn" }) {
  const bigClass = tone === "warn" ? "text-amber-300" : tone === "good" ? "text-emerald-300" : "text-white";
  return (
    <div>
      <p className="text-[var(--text-dim)] text-[10px] uppercase tracking-widest font-bold">{label}</p>
      <p className={`text-sm font-bold mt-1.5 tabular ${bigClass}`}>{big}</p>
      <p className="text-[var(--text-faint)] text-[10.5px] mt-0.5 tabular truncate">{sub}</p>
    </div>
  );
}

function FunnelRow({ icon: Icon, label, value, max, last }: { icon: React.ComponentType<{ className?: string; strokeWidth?: number }>; label: string; value: number; max: number; last?: boolean }) {
  const pct = max > 0 ? Math.max(2, Math.round((value / max) * 100)) : 2;
  return (
    <div className={`py-2.5 ${last ? "" : "border-b border-[var(--border-1)]"}`}>
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2.5">
          <Icon strokeWidth={1.75} className="w-3.5 h-3.5 text-[var(--text-dim)]" />
          <span className="text-[var(--text)] text-sm font-medium">{label}</span>
        </div>
        <span className="text-white text-sm font-bold tabular">{value}</span>
      </div>
      <div className="w-full h-1 bg-[var(--bg-elev-3)] rounded-full overflow-hidden">
        <div className="h-full bg-gradient-to-r from-emerald-600/70 to-emerald-400/70" style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}

function CountryTile({ flag, country, active, highlight }: { flag: string; country: string; active: number; highlight: string }) {
  const hasAny = active > 0;
  return (
    <div className={`rounded-md border p-4 transition-all ${hasAny ? "bg-emerald-500/[0.05] border-emerald-500/25 hover:border-emerald-500/40" : "bg-[var(--bg-elev-1)] border-[var(--border-2)] hover:border-[var(--border-3)]"}`}>
      <div className="flex items-start justify-between">
        <span className="text-2xl">{flag}</span>
        <span className={`text-[10px] uppercase tracking-wider font-bold ${hasAny ? "text-emerald-300" : "text-[var(--text-dim)]"}`}>
          {hasAny ? `${active} active` : "Not yet"}
        </span>
      </div>
      <p className="text-white text-sm font-bold mt-3">{country}</p>
      <p className="text-[var(--text-dim)] text-xs mt-1">{highlight}</p>
    </div>
  );
}

function CheckItem({ ok, title, okHint, missingHint }: { ok: boolean; title: string; okHint: string; missingHint: string }) {
  return (
    <li className="flex items-start gap-2.5">
      <span className={`mt-0.5 ${ok ? "text-emerald-400" : "text-amber-400"}`}>
        {ok ? <CheckCircle2 className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
      </span>
      <div className="flex-1 min-w-0">
        <p className="text-[var(--text)] font-semibold">{title}</p>
        <p className="text-[var(--text-dim)] text-xs mt-0.5">{ok ? okHint : missingHint}</p>
      </div>
    </li>
  );
}
