ALTER TABLE "SearchBrief" ADD COLUMN IF NOT EXISTS "discoveryCursor" JSONB;
ALTER TABLE "SearchBrief" ADD COLUMN IF NOT EXISTS "cooldownUntil" TIMESTAMP(3);
ALTER TABLE "SearchBrief" ADD COLUMN IF NOT EXISTS "emptyRunStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SearchBrief" ADD COLUMN IF NOT EXISTS "exhaustedAt" TIMESTAMP(3);
