-- Autopilot core tables
CREATE TABLE IF NOT EXISTS "SearchBrief" (
    "id"               TEXT NOT NULL,
    "name"             TEXT NOT NULL,
    "niche"            TEXT NOT NULL,
    "city"             TEXT,
    "country"          TEXT NOT NULL DEFAULT 'FR',
    "query"            TEXT,
    "minRating"        DOUBLE PRECISION,
    "minReviews"       INTEGER,
    "maxPerRun"        INTEGER NOT NULL DEFAULT 5,
    "qualityThreshold" INTEGER NOT NULL DEFAULT 6,
    "autoGenerate"     BOOLEAN NOT NULL DEFAULT TRUE,
    "autoSchedule"     BOOLEAN NOT NULL DEFAULT TRUE,
    "active"           BOOLEAN NOT NULL DEFAULT TRUE,
    "lastRunAt"        TIMESTAMP(3),
    "totalDiscovered"  INTEGER NOT NULL DEFAULT 0,
    "totalQualified"   INTEGER NOT NULL DEFAULT 0,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,
    CONSTRAINT "SearchBrief_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DiscoveryRun" (
    "id"          TEXT NOT NULL,
    "briefId"     TEXT NOT NULL,
    "startedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt"  TIMESTAMP(3),
    "status"      TEXT NOT NULL DEFAULT 'running',
    "found"       INTEGER NOT NULL DEFAULT 0,
    "emailsFound" INTEGER NOT NULL DEFAULT 0,
    "created"     INTEGER NOT NULL DEFAULT 0,
    "qualified"   INTEGER NOT NULL DEFAULT 0,
    "scheduled"   INTEGER NOT NULL DEFAULT 0,
    "errors"      JSONB,
    "notes"       TEXT,
    CONSTRAINT "DiscoveryRun_pkey" PRIMARY KEY ("id")
);

-- Prospect source/audit fields
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "source"        TEXT;
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "sourceQuery"   TEXT;
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "externalId"    TEXT;
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "autoScheduled" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Prospect" ADD COLUMN IF NOT EXISTS "briefId"       TEXT;

CREATE INDEX IF NOT EXISTS "Prospect_source_idx"     ON "Prospect"("source");
CREATE INDEX IF NOT EXISTS "Prospect_externalId_idx" ON "Prospect"("externalId");
CREATE INDEX IF NOT EXISTS "Prospect_briefId_idx"    ON "Prospect"("briefId");
CREATE INDEX IF NOT EXISTS "DiscoveryRun_briefId_idx" ON "DiscoveryRun"("briefId");
CREATE INDEX IF NOT EXISTS "SearchBrief_active_idx"  ON "SearchBrief"("active");

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Prospect_briefId_fkey') THEN
        ALTER TABLE "Prospect" ADD CONSTRAINT "Prospect_briefId_fkey"
            FOREIGN KEY ("briefId") REFERENCES "SearchBrief"("id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'DiscoveryRun_briefId_fkey') THEN
        ALTER TABLE "DiscoveryRun" ADD CONSTRAINT "DiscoveryRun_briefId_fkey"
            FOREIGN KEY ("briefId") REFERENCES "SearchBrief"("id") ON DELETE CASCADE;
    END IF;
END$$;
